orbs:
  node: circleci/node@5.2.0

version: 2.1

parameters:
  node_version:
    type: string
    default: '18.12.0'

commands:
  install_deps:
    steps:
      - node/install-packages:
          pkg-manager: yarn
          cache-version: v1-all
          cache-only-lockfile: true
          app-dir: ~/repo
          override-ci-command: yarn install --pure-lockfile --no-progress
      - run: |
          sudo apt update -q
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install postgresql-12

jobs:
  build:
    executor:
      name: node/default
      tag: <<pipeline.parameters.node_version>>
    working_directory: ~/repo
    steps:
      - checkout
      - install_deps
      - run: yarn build
      - run: sudo yarn test
      - run: yarn type-check
      - run: yarn lint:ci
